database/migrations/2018_02_09_080041_add_rank_to_users.php
database/migrations/2018_02_09_081420_create_breeds_table.php
database/migrations/2018_02_09_082439_create_selections_table.php
database/migrations/2018_02_09_083002_add_selection_id_to_users_table.php

Added table migrations which created the following tables:
- Users Table
- Password Resets Table
- Selections Table
- Breeds Table

DOG-1 Created Basic Table Migrations

---

app/Http/Controllers/NotificationController.php
app/Notifications/PetArrived.php
composer.json
composer.lock
routes/api.php

Allows a user to send a custom laravel notification email to a recipient, given an email address.  The email message is styled using the Laravel Notification libray.

Email notification - Custom Lavel email message and route

---

app/Http/Controllers/BreedStatusController.php
app/Http/Controllers/Controller.php
public/js/custom.js
resources/views/welcome.blade.php
routes/web.php

Adds two function:
- getHomeView  which returns the welcome.blade with data to populate breeds.
- getAllBreeds which reads a list from json and returns a mapped array

Breed data

---

app/Http/Controllers/BreedStatusController.php
public/js/custom.js
resources/views/partials/master.blade.php
resources/views/welcome.blade.php
routes/web.php

Adds a function which can compare and output the distances between zip code strings.

zip_code_filter - Adds ability to get distances between zip codes

---

app/Http/Controllers/BreedStatusController.php
routes/web.php

- Adds function for retreiving 100 records for local breeds by a single zip code

api-breed-query Created function to query for 100 records from external api

---

app/Breed.php
app/Http/Controllers/BreedStatusController.php
app/Selection.php
app/User.php
composer.json
composer.lock
database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2018_03_11_012138_rename_columns_to_selections_table.php
database/migrations/2018_03_11_024012_add_breed_id_column_to_breeds_table.php
database/seeds/BreedsTableSeeder.php
database/seeds/DatabaseSeeder.php
routes/web.php

- Adds function getBreedIdForDatabase
- Adds functionality to store users email, breed and miles preferences to DB
- Creates Breeds, Selections, Users Models
- Adds Relationships for all three tables

save-user-to-database Stores initial user information and selection criteria

---

app/Breed.php
app/Http/Controllers/BreedStatusController.php
app/Http/Controllers/DistanceController.php
app/Http/Controllers/FormController.php
app/Selection.php
routes/web.php

- Created function saveMaxBreedIdToSelectionsTable
- Created function getLargestBreedId
Together these functions are able to sort through the initial api records and find the maxiumum pet Id.  The highest pet Id represents the most recent entry.  The end result is storing the most recent/ max entry in the database.

sort-largest-breed Created functionality to store highest breed

---

app/Http/Controllers/BreedStatusController.php
app/Http/Controllers/FormController.php
app/Selection.php
database/migrations/2018_03_11_073327_add_zip_column_to_selections_table.php
routes/web.php

Adds three functions 
- sortRecordsIds
- getRecordsLargerThanBreedId
- getUpdatedBreedArray
Together these three functions retreive datase information in unison with making an api call to determine if new breeds have been entered into the system.

compare-two-api-calls Functionality to find highest breed_id between calls

---

app/Http/Controllers/BreedStatusController.php
app/Http/Controllers/DistanceController.php
app/Http/Controllers/NotificationController.php
routes/web.php

Adds functionality for checking the distance between zip codes.

Check distance Adds functionality to filter distance

---

app/Console/Commands/CallNotificationRoute.php
app/Console/Kernel.php
app/Http/Controllers/BreedStatusController.php
routes/web.php
storage/output.txt

This PR creates the following:
- Creates a php artisan command called route:call 
- Creates a Task Scheduler to run sendNotification function
The newly created route:call command takes a uri argument and can be called using  route:call {uri}.  This command is used in the task scheduler to trigger BreedStatusController@sendNotification

Scheduler Schedule notifications to be sent to users

---

app/Http/Controllers/FormController.php
routes/web.php

Adds the highest breed_id value of the initial post request, this request is sent by a user who fills out the landing page form.  These changes allow a user to save their highest breed_id from an api call to the database.

landing-page-post Minor Changes to Landing Page Post Logic

---

app/Console/Kernel.php
app/Found_Dog.php
app/Http/Controllers/BreedStatusController.php
app/Http/Controllers/NotificationController.php
database/migrations/2018_03_24_211333_create_found_dogs_table.php
database/migrations/2018_03_25_002106_add_distance_column_to_found_dogs.php
database/migrations/2018_03_25_003117_remove_distance_column_from_found_dogs.php
database/seeds/DatabaseSeeder.php
database/seeds/found_dogsTableSeeder.php
routes/web.php

Adds a route which returns a page with the data of all dogs to be displayed to the user.

dynamic-route-creation Added dynamic route for results page

---

database/seeds/found_dogsTableSeeder.php

This fix replaced old pet id's with workings ones as of 05-01-18.

Hotfix - Updated Seeder to reflect valid id's

---

database/seeds/found_dogsTableSeeder.php

Updates seeder to reflect current dog id's for api.

hotfix-seeder-change-ids Added new dog id's to database seeder

---

app/Services/DogDataService.php
app/Services/NotificationService.php
database/factories/FoundDogsFactory.php
routes/web.php
storage/output.txt
tests/Unit/DogDataServiceTest.php

`- Added Multiple Test functions`
`- Refactored DogDataService.php to remove all Global Variables`
`- Create factory for Found_Dogs Table`
`Testing/Factories`

add-tests-for-DogDataService Added missing tests for function in DogDataService.php

---

app/Exceptions/InvalidPetIdException.php
app/Services/DogDataService.php
app/Services/ExternalPetApiService.php
database/seeds/found_dogsTableSeeder.php
routes/web.php
tests/Api/ExternalPetApiServiceTest.php
tests/Unit/DogDataServiceTest.php
tests/Unit/FormControllerTest.php

- Adds all unit tests for each function in ExternalPetApiService.php
- Updates a single seeder id which was degredated.

add-tests-to-external-pet-api-service Writes tests for ExternalPetApiService

---

.gitignore
app/Console/Kernel.php
app/Selection.php
app/Services/DogDataService.php
app/Services/NotificationService.php
database/seeds/AllTableDataSeeder.php
storage/output.txt
tests/Api/ExternalZipApiServiceTest.php
tests/Api/NotificationServiceTest.php

- Adds test class NotificationService Test
- Fixes a bug in NotificationService@sendNotification
This class holds all test functions for NotificationService.php.  The bug was passing a null value as a function argument.

add-tests-to-notification-service

---

public/css/app.css
resources/assets/sass/_custom.scss

Check for mobile responsiveness on home page and results page and make fixes where necessary.
All looks mobile responsive now - however, on a phone it may look different so later to truly test this, we must check on users phones.

FASP-16 mobile responsiveness 

---

resources/views/welcome.blade.php

In the 1-3 steps section, remove "Enter a Breed" and replace with "Enter a Distance" (Enter a Location, Enter a Distance, Get Notified)

FASP-17 edited 3 step section to remove enter breed

---

app/Http/Controllers/FormController.php
routes/web.php
tests/Unit/FormControllerTest.php

- Adds changed to test function for branch FASP-33.

HOTFIX - FASP-33

---

app/Providers/AppServiceProvider.php

- Checks env for production and changes https schema accordingly

FASP-44 Added https schema to env url

---

app/Providers/AppServiceProvider.php

- Fixe issue where webpage renders without styling

HOTFIX-REMOVE-HTTPS-SCHEMA Removed https from AppServiceProvider

---

public/css/app.css
resources/assets/sass/_custom.scss

- Fixes the horizontal scroll issue on the websites pages
- On the home page, try to use the mouse pad to move the web page left and right. You should not be able to and the page should be unaffected by your movements.

FASP-42 fixed horizonta scroll problem

---

resources/views/partials/master.blade.php

- The original meta description for this site was not displaying on google search, so I edited the meta description for site so that google would use this desciption.

FASP-39a edited meta description for site

---

app/Found_Dog.php

- Sorts the database collection to sort by descending from updated_at date.

FASP-29 Display Results Page Data in Order of New to Old

---

resources/views/partials/footer.blade.php
resources/views/welcome.blade.php

- Adds Scrolling Functionality and clickable icons
- Adds 'Powered By Petfinder' to footer'

FASP-36 Add button functionality to icons on landing page

---

resources/views/welcome.blade.php

-  Adds key words to our Webpage specific to our site and that are highly searched
- The Home Page Title and 3 user experiences have been changed to add high ranked key words such as "find / adopt a puppy near me" and "for free" and including our website name more "findashelterpuppy.com"

modified home page title and references section with keywords

---

public/css/app.css
public/js/custom.js
resources/assets/sass/_custom.scss
resources/views/partials/master.blade.php
resources/views/partials/nav.blade.php
resources/views/results.blade.php

- Created a new navigation blade (nav.blade.php) and included it in the master blade so all future pages will have this new navbar
- The navbar is designed with a dark background and white menu text providing a strong contrast and to ensure it will be easily readable on future unknown pages on this site that may have unknown background colors
- It is "Sticky" so as you scroll down the pages, it will always stay at the top for easy access to new pages. 
- It's mobile responsive
- pull new changes from master
- switch to my branch FASP-87
- View the welcome.blade.php to see the navbar
- Play with the navbar and the page (when you scroll, the nav sticks to the top and turns from a gradient faded out color to a solid color, when hovering, the text changes orange, on mobile, the menu collapses …

FASP-87 New Nav System
